window.RACE_CALENDAR_ENTRIES = [
  {
    "title": "Corrida 90 Anos do 6º BPM",
    "date": "2026-04-12",
    "time": "10:00",
    "location": "Rio Grande - RS",
    "distances": ["3KM"],
    "circuito": "",
    "signupUrl": "https://www.minhasinscricoes.com.br/Evento/Corrida90Anosdo6BPM",
    "signupLabel": "Inscrições abertas",
    "notes": ""
  },
  {
    "title": "2ª Meia Maratona do Choque",
    "date": "2026-04-12",
    "time": "07:00",
    "location": "Pelotas - RS",
    "distances": ["5KM", "10KM", "21KM"],
    "circuito": "",
    "signupUrl": "https://ecommerce.sesc-rs.com.br/ecommerce.paginaprodutoevento.aspx?3085,2%C2%AA-MEIA-MARATONA-DO-CHOQUE--PELOTAS",
    "signupLabel": "Inscrições abertas",
    "notes": ""
  },
  {
    "title": "Corrida Prime Haus Running",
    "date": "2026-04-19",
    "time": "17:00",
    "location": "Rio Grande - RS",
    "distances": ["5KM"],
    "circuito": "",
    "signupUrl": "https://docs.google.com/forms/d/1Wn_uiBi6S_oPFkCZBq0_3QS-SBalaswzuHnDkEf-D0Q/viewform?fbclid=PAZnRzaAQ9S1pleHRuA2FlbQIxMQBzcnRjBmFwcF9pZA8xMjQwMjQ1NzQyODc0MTQAAaegOS5FcDXu0Ha61P5BYc6R9jhTLg3ACeQVzqEID0QoD-hbcUuZkuQ1dqJfUA_aem_Ut5RmXbTAb4BOYzBX1dMww&edit_requested=true&utm_source=ig&utm_medium=social&utm_content=link_in_bio",
    "signupLabel": "Inscrições abertas",
    "notes": ""
  },
  {
    "title": "Corrida do SESI",
    "date": "2026-05-01",
    "time": "08:00",
    "location": "Rio Grande - RS",
    "distances": ["5KM", "10KM"],
    "circuito": "",
    "signupUrl": "https://corridadosesi.sesirs.org.br/",
    "signupLabel": "Inscrições abertas",
    "notes": ""
  },
  {
    "title": "4º Desafio Não Tem Garantia - Night Run",
    "date": "2026-05-02",
    "time": "18:00",
    "location": "Vila da Quinta - Rio Grande - RS",
    "distances": ["5KM", "10KM"],
    "circuito": "",
    "signupUrl": "https://gruponaotemgarantia.com.br/",
    "signupLabel": "Inscrições abertas",
    "notes": ""
  },
  {
    "title": "Circuito Estadual do Sesc",
    "date": "2026-05-17",
    "time": "09:00",
    "location": "Rio Grande - RS",
    "distances": ["3KM", "5KM", "10KM"],
    "circuito": "",
    "signupUrl": "https://ecommerce.sesc-rs.com.br/ecommerce.catalogoprodutos.aspx?EVE,0,12,0,,",
    "signupLabel": "Inscrições abertas",
    "notes": ""
  },
  {
    "title": "Dia do Desafio",
    "date": "2026-05-26",
    "time": "",
    "location": "Rio Grande - RS",
    "distances": ["A definir"],
    "circuito": "",
    "signupUrl": "",
    "signupLabel": "",
    "notes": "Aguardando mais informações"
  },
  {
    "title": "Corrida da Unimed",
    "date": "2026-06-21",
    "time": "15:00",
    "location": "Rio Grande - RS",
    "distances": ["3KM", "5KM", "10KM"],
    "circuito": "sim",
    "signupUrl": "",
    "signupLabel": "",
    "notes": ""
  },
  {
    "title": "Corrida dos Bombeiros",
    "date": "2026-07-05",
    "time": "15:00",
    "location": "Rio Grande - RS",
    "distances": ["3KM", "5KM", "10KM"],
    "circuito": "sim",
    "signupUrl": "",
    "signupLabel": "",
    "notes": ""
  },
  {
    "title": "Night Run",
    "date": "2026-08-15",
    "time": "20:00",
    "location": "Rio Grande - RS",
    "distances": ["5KM"],
    "circuito": "",
    "signupUrl": "",
    "signupLabel": "",
    "notes": "Aguardando mais informações"
  },
  {
    "title": "Corrida da Força Tática",
    "date": "2026-08-29",
    "time": "16:00",
    "location": "Rio Grande - RS",
    "distances": ["3KM", "5KM"],
    "circuito": "",
    "signupUrl": "",
    "signupLabel": "",
    "notes": "Aguardando mais informações"
  },
  {
    "title": "Corrida Panapana",
    "date": "2026-09-13",
    "time": "",
    "location": "Rio Grande - RS",
    "distances": ["3KM", "5KM"],
    "circuito": "",
    "signupUrl": "",
    "signupLabel": "",
    "notes": "Aguardando mais informações"
  },
  {
    "title": "Meia do Pontal",
    "date": "2026-09-27",
    "time": "08:00",
    "location": "Rio Grande - RS",
    "distances": ["A definir"],
    "circuito": "",
    "signupUrl": "",
    "signupLabel": "",
    "notes": "Aguardando mais informações"
  },
  {
    "title": "Corrida do Batom",
    "date": "2026-10-18",
    "time": "10:00",
    "location": "Rio Grande - RS",
    "distances": ["3KM", "Caminhada 3KM", "Maratoninha"],
    "circuito": "",
    "signupUrl": "",
    "signupLabel": "",
    "notes": "Aguardando mais informações"
  },
  {
    "title": "Corrida da Marinha",
    "date": "2026-11-01",
    "time": "08:00",
    "location": "Rio Grande - RS",
    "distances": ["5KM", "10KM"],
    "circuito": "sim",
    "signupUrl": "",
    "signupLabel": "",
    "notes": ""
  },
  {
    "title": "Corrida do Porto",
    "date": "2026-11-15",
    "time": "09:00",
    "location": "Rio Grande - RS",
    "distances": ["3KM", "5KM", "10KM"],
    "circuito": "sim",
    "signupUrl": "",
    "signupLabel": "",
    "notes": ""
  },
  {
    "title": "Corrida dos Fuzileiros",
    "date": "2026-11-29",
    "time": "08:00",
    "location": "Rio Grande - RS",
    "distances": ["A confirmar"],
    "circuito": "",
    "signupUrl": "",
    "signupLabel": "",
    "notes": "Aguardando mais informações"
  },
  {
    "title": "Corrida Academia Prime",
    "date": "2026-12-06",
    "time": "09:00",
    "location": "Rio Grande - RS",
    "distances": ["5KM"],
    "circuito": "",
    "signupUrl": "",
    "signupLabel": "",
    "notes": "Aguardando mais informações"
  },
  {
    "title": "Volta da Ilha dos Marinheiros",
    "date": "2026-12-13",
    "time": "07:00",
    "location": "Ilha dos Marinheiros - Rio Grande - RS",
    "distances": ["3KM", "5KM", "24KM", "Caminhada 3KM"],
    "circuito": "",
    "signupUrl": "",
    "signupLabel": "",
    "notes": "Aguardando mais informações"
  },
  {
    "title": "Tchau 2026",
    "date": "2026-12-20",
    "time": "08:00",
    "location": "Rio Grande - RS",
    "distances": ["3KM", "5KM", "10KM"],
    "circuito": "sim",
    "signupUrl": "",
    "signupLabel": "",
    "notes": ""
  },
  {
    "title": "Maratona Internacional de POA",
    "date": "2026-05-30",
    "time": "07:00",
    "location": "Porto Alegre - RS",
    "distances": ["5KM", "10KM", "21KM", "42KM"],
    "circuito": "",
    "signupUrl": "",
    "signupLabel": "Inscrições abertas",
    "notes": ""
  }
];
